version: "3.8"
services:
  rstudio:
    build:
      context: . 
    ports:
      - 8787:8787
    environment:
      - ROOT=true
      - PASSWORD=123
    env_file: .env
    volumes:
      - ${PACTA_CORE}:/home/rstudio/pactaCore
      - ${PACTA_ANALYSIS}:/home/rstudio/PACTA_analysis
      - ${PACTA_DATA}:/home/rstudio/pacta-data
